"""empty message

Revision ID: c8c454ee90c5
Revises: 0897e6689e2b
Create Date: 2018-11-24 09:02:11.346477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c454ee90c5'
down_revision = '0897e6689e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_requests', sa.Column('target_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_requests', 'target_date')
    # ### end Alembic commands ###
